platform :ios, '8.0'
    target 'ZTBaseProject' do
pod 'AFNetworking', '~> 3.0.4'
pod 'IHKeyboardAvoiding', '~> 2.5'
pod 'MBProgressHUD', '~> 0.8'
#pod 'AFSoundManager'
#pod 'JSBadgeView'
pod 'Masonry'
pod 'BlocksKit', '~> 2.2.5'
pod 'JSONModel', '~> 1.1.2'
pod 'TTTAttributedLabel', '~> 1.13.4'
#pod 'SDWebImage', '~> 3.7.3'
#pod 'MWPhotoBrowser', '~> 2.1.1'
pod 'CocoaLumberjack', '~> 2.2.0'
#pod 'ZBarSDK', '~> 1.3.1'
#pod 'UMengAnalytics-NO-IDFA'
#pod 'GetuiSDK', '~> 1.3.2'
pod 'UICKeyChainStore', '~> 2.1.0'
pod 'MJRefresh', '~> 3.1.0'
#pod 'BaiduMapKit', '~> 2.9.1'
#pod 'libPhoneNumber-iOS', '~> 0.8.10'
pod 'GDataXML-HTML', '~> 1.3.0'
#pod 'KeychainAccess', '~> 2.3.5'
#pod 'KeychainItemWrapper', '~> 1.2'
end

